version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./path/to/your/nginx/conf:/etc/nginx/conf.d
      - ./path/to/your/static/files:/usr/share/nginx/html

volumes:
  db-data:
