version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./client/build:/usr/share/nginx/html
volumes:
  db-data:
